name: Build MongoDbQueueService

on: 
  push: 
    tags: 
    - '*'

jobs:
  build:
    name: Building the solution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore MongoDbQueueService.sln

      - name: Create nuget package
        run: dotnet pack --configuration Release
                /p:NuGetVersion=6.0.x
                /p:AssemblyVersion=${{ github.ref }}
                /p:Version=${{ github.ref_name }}
                /p:PackageReleaseNotes="See http://github.com/AboimPinto/MongoDbQueueService/releases/tag/${{ github.event.release.tag_name }}" 
      
      - name: Archive nuget package
        uses: actions/upload-artifact@v3
        with: 
          name: MongoDbQueueService
          path: ./MongoDbQueueService/bin/Release/MongoDbQueueService.${{ github.event.release.tag_name }}.nupkg

      - name: Publish nuget package
        run: dotnet nuget push ./MongoDbQueueService/bin/Release/MongoDbQueueService.${{ github.event.release.tag_name }}.nupkg
              --api-key ${{ secrets.MONGO_DB_QUEUE_SERVICE_KEY }}
              --source https://api.nuget.org/v3/index.json
              --no-symbols true

      